"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Topbar from "./topbar";
import { ReduxProvider } from "app/redux/features/provider.js";
import { Provider } from "react-redux";
import { Analytics } from '@vercel/analytics/react';

import { store } from "app/redux/store.js";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8376660329507482"
     crossorigin="anonymous"></script></head>
      <body
        className={`{inter.className} border-gray-200 bg-gray-50 dark:bg-gray-900 dark:border-gray-700 `}
      >
        <ReduxProvider store={store}>
          <Topbar />
          <Navbar />
          {children}
          <Analytics />
        </ReduxProvider>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet"></link>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
        
      </body>
    </html>
  );
}
